//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MpathY.Content.App_LocalResources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MpathY.Content.App_LocalResources.Lang.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is offered in 4 languages, including English, Arabic, Burmese, and Dari, so that users could browse the website in their
        ///                                native language. The website aims to help refugees, who live in Victoria to locate nine different types of support services,
        ///                                which are provided by Non-Government Organisations (NGOs) including job support, health support, food support, volunteer support, English support,
        ///                                humanit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Us_Content {
            get {
                return ResourceManager.GetString("About_Us_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The open datasets we used for this website include:.
        /// </summary>
        public static string About_Us_Thanks {
            get {
                return ResourceManager.GetString("About_Us_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Volunteer centres in Victoria.
        /// </summary>
        public static string About_Us_Thanks_One {
            get {
                return ResourceManager.GetString("About_Us_Thanks_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Organisations providing Humanitarian Settlement Services in Victoria.
        /// </summary>
        public static string About_Us_Thanks_Three {
            get {
                return ResourceManager.GetString("About_Us_Thanks_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Organisations providing free and cheap life services in Victoria.
        /// </summary>
        public static string About_Us_Thanks_Two {
            get {
                return ResourceManager.GetString("About_Us_Thanks_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accomodation.
        /// </summary>
        public static string Accomodation {
            get {
                return ResourceManager.GetString("Accomodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درى.
        /// </summary>
        public static string Burmese {
            get {
                return ResourceManager.GetString("Burmese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_Clear_Address {
            get {
                return ResourceManager.GetString("Button_Clear_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear checkbox.
        /// </summary>
        public static string Button_Clear_Checkbox {
            get {
                return ResourceManager.GetString("Button_Clear_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close_Popup {
            get {
                return ResourceManager.GetString("Button_Close_Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Button_Language_Choice {
            get {
                return ResourceManager.GetString("Button_Language_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Message_Close {
            get {
                return ResourceManager.GetString("Button_Message_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Message_Send {
            get {
                return ResourceManager.GetString("Button_Message_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search_Address {
            get {
                return ResourceManager.GetString("Button_Search_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahasa Indonesia.
        /// </summary>
        public static string Conversation_Direction {
            get {
                return ResourceManager.GetString("Conversation_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation Starter.
        /// </summary>
        public static string Conversation_Starter {
            get {
                return ResourceManager.GetString("Conversation_Starter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to start a conversation in your own language? We can help you!.
        /// </summary>
        public static string Conversation_Starter_Slogan {
            get {
                return ResourceManager.GetString("Conversation_Starter_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug and Alcohol Counselling.
        /// </summary>
        public static string Counselling {
            get {
                return ResourceManager.GetString("Counselling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan for your children&apos;s education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Humanitarian Settlement Services.
        /// </summary>
        public static string Education1 {
            get {
                return ResourceManager.GetString("Education1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string Email_Send {
            get {
                return ResourceManager.GetString("Email_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empathi.
        /// </summary>
        public static string Empathi {
            get {
                return ResourceManager.GetString("Empathi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Support.
        /// </summary>
        public static string English_Lesson {
            get {
                return ResourceManager.GetString("English_Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Support.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get there?.
        /// </summary>
        public static string Get_There {
            get {
                return ResourceManager.GetString("Get_There", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Top.
        /// </summary>
        public static string Go_Top {
            get {
                return ResourceManager.GetString("Go_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the supermarket?.
        /// </summary>
        public static string Grocery {
            get {
                return ResourceManager.GetString("Grocery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Support Services.
        /// </summary>
        public static string Heading_Search_NGO {
            get {
                return ResourceManager.GetString("Heading_Search_NGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Support.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.g. Carnegie Station.
        /// </summary>
        public static string Hint_Location {
            get {
                return ResourceManager.GetString("Hint_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can click these red pins in the map to view more information..
        /// </summary>
        public static string Hint_Red_Pin {
            get {
                return ResourceManager.GetString("Hint_Red_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search an address here:.
        /// </summary>
        public static string Hint_Search_Address {
            get {
                return ResourceManager.GetString("Hint_Search_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select a sentence from the box below and we translate it for you with a voiceover in English!.
        /// </summary>
        public static string Hint_Start_Conversation {
            get {
                return ResourceManager.GetString("Hint_Start_Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humanitarian Settlement.
        /// </summary>
        public static string Humanitarian_Settlement {
            get {
                return ResourceManager.GetString("Humanitarian_Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahasa Indonesia.
        /// </summary>
        public static string Indonesian {
            get {
                return ResourceManager.GetString("Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your location here:.
        /// </summary>
        public static string Input_Location {
            get {
                return ResourceManager.GetString("Input_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Support.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn English.
        /// </summary>
        public static string Learn_English {
            get {
                return ResourceManager.GetString("Learn_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate your nearest service to learn English..
        /// </summary>
        public static string Learn_English1 {
            get {
                return ResourceManager.GetString("Learn_English1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal advice.
        /// </summary>
        public static string Legal_Advice {
            get {
                return ResourceManager.GetString("Legal_Advice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for?.
        /// </summary>
        public static string Looking {
            get {
                return ResourceManager.GetString("Looking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical help.
        /// </summary>
        public static string Medical_Help {
            get {
                return ResourceManager.GetString("Medical_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch with health support.
        /// </summary>
        public static string Medical_Help1 {
            get {
                return ResourceManager.GetString("Medical_Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Write your message.
        /// </summary>
        public static string Message_Step_One {
            get {
                return ResourceManager.GetString("Message_Step_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Press the button.
        /// </summary>
        public static string Message_Step_Three {
            get {
                return ResourceManager.GetString("Message_Step_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Select the language:.
        /// </summary>
        public static string Message_Step_Two {
            get {
                return ResourceManager.GetString("Message_Step_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Message_Translate {
            get {
                return ResourceManager.GetString("Message_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation result.
        /// </summary>
        public static string Message_Translation_Result {
            get {
                return ResourceManager.GetString("Message_Translation_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to buy ticket?.
        /// </summary>
        public static string Myki {
            get {
                return ResourceManager.GetString("Myki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need job?.
        /// </summary>
        public static string Need_Job {
            get {
                return ResourceManager.GetString("Need_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your nearest service to get a job..
        /// </summary>
        public static string Need_Job1 {
            get {
                return ResourceManager.GetString("Need_Job1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to မြန်မာ.
        /// </summary>
        public static string Pashto {
            get {
                return ResourceManager.GetString("Pashto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number:.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language:.
        /// </summary>
        public static string Popup_Language_Choice {
            get {
                return ResourceManager.GetString("Popup_Language_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Support Services.
        /// </summary>
        public static string Search_NGO {
            get {
                return ResourceManager.GetString("Search_NGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for help? We can help you find them!.
        /// </summary>
        public static string Search_NGO_Slogan {
            get {
                return ResourceManager.GetString("Search_NGO_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Topic.
        /// </summary>
        public static string Select_Topic {
            get {
                return ResourceManager.GetString("Select_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose any of the following topics for conversation!.
        /// </summary>
        public static string Select_Topic_Slogan {
            get {
                return ResourceManager.GetString("Select_Topic_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your message to:.
        /// </summary>
        public static string Send_Your_Message_To {
            get {
                return ResourceManager.GetString("Send_Your_Message_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Sentence1 {
            get {
                return ResourceManager.GetString("Sentence1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the nearest tram or bus stop?.
        /// </summary>
        public static string Sentence10 {
            get {
                return ResourceManager.GetString("Sentence10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sentence11 {
            get {
                return ResourceManager.GetString("Sentence11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string Sentence12 {
            get {
                return ResourceManager.GetString("Sentence12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much does this cost?.
        /// </summary>
        public static string Sentence13 {
            get {
                return ResourceManager.GetString("Sentence13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t understand.
        /// </summary>
        public static string Sentence14 {
            get {
                return ResourceManager.GetString("Sentence14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I feel sick.
        /// </summary>
        public static string Sentence15 {
            get {
                return ResourceManager.GetString("Sentence15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a place to stay.
        /// </summary>
        public static string Sentence16 {
            get {
                return ResourceManager.GetString("Sentence16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need doctor.
        /// </summary>
        public static string Sentence17 {
            get {
                return ResourceManager.GetString("Sentence17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need food.
        /// </summary>
        public static string Sentence18 {
            get {
                return ResourceManager.GetString("Sentence18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need job.
        /// </summary>
        public static string Sentence19 {
            get {
                return ResourceManager.GetString("Sentence19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are you?.
        /// </summary>
        public static string Sentence2 {
            get {
                return ResourceManager.GetString("Sentence2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need mental health support.
        /// </summary>
        public static string Sentence20 {
            get {
                return ResourceManager.GetString("Sentence20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need money.
        /// </summary>
        public static string Sentence21 {
            get {
                return ResourceManager.GetString("Sentence21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need sanitary pad.
        /// </summary>
        public static string Sentence22 {
            get {
                return ResourceManager.GetString("Sentence22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to buy bread.
        /// </summary>
        public static string Sentence23 {
            get {
                return ResourceManager.GetString("Sentence23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to learn English.
        /// </summary>
        public static string Sentence24 {
            get {
                return ResourceManager.GetString("Sentence24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to make a phone call.
        /// </summary>
        public static string Sentence25 {
            get {
                return ResourceManager.GetString("Sentence25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need visa support.
        /// </summary>
        public static string Sentence26 {
            get {
                return ResourceManager.GetString("Sentence26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need water.
        /// </summary>
        public static string Sentence27 {
            get {
                return ResourceManager.GetString("Sentence27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this halal?.
        /// </summary>
        public static string Sentence28 {
            get {
                return ResourceManager.GetString("Sentence28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is very cold.
        /// </summary>
        public static string Sentence29 {
            get {
                return ResourceManager.GetString("Sentence29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am good.
        /// </summary>
        public static string Sentence3 {
            get {
                return ResourceManager.GetString("Sentence3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time is it?.
        /// </summary>
        public static string Sentence30 {
            get {
                return ResourceManager.GetString("Sentence30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need financial support.
        /// </summary>
        public static string Sentence31 {
            get {
                return ResourceManager.GetString("Sentence31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is the rent.
        /// </summary>
        public static string Sentence32 {
            get {
                return ResourceManager.GetString("Sentence32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to be a volunteer.
        /// </summary>
        public static string Sentence33 {
            get {
                return ResourceManager.GetString("Sentence33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a volunteer to help me.
        /// </summary>
        public static string Sentence34 {
            get {
                return ResourceManager.GetString("Sentence34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to quit drinking.
        /// </summary>
        public static string Sentence35 {
            get {
                return ResourceManager.GetString("Sentence35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need to quit drug.
        /// </summary>
        public static string Sentence36 {
            get {
                return ResourceManager.GetString("Sentence36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can you help me to settle here.
        /// </summary>
        public static string Sentence37 {
            get {
                return ResourceManager.GetString("Sentence37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help me!.
        /// </summary>
        public static string Sentence4 {
            get {
                return ResourceManager.GetString("Sentence4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a refugee.
        /// </summary>
        public static string Sentence5 {
            get {
                return ResourceManager.GetString("Sentence5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t speak English very well.
        /// </summary>
        public static string Sentence6 {
            get {
                return ResourceManager.GetString("Sentence6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the toilet?.
        /// </summary>
        public static string Sentence7 {
            get {
                return ResourceManager.GetString("Sentence7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get to this address?.
        /// </summary>
        public static string Sentence8 {
            get {
                return ResourceManager.GetString("Sentence8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the nearest train station?.
        /// </summary>
        public static string Sentence9 {
            get {
                return ResourceManager.GetString("Sentence9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start conversation.
        /// </summary>
        public static string Start_Conversation {
            get {
                return ResourceManager.GetString("Start_Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When does the train leave?.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is the station?.
        /// </summary>
        public static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to vaccinate?.
        /// </summary>
        public static string Vaccinate {
            get {
                return ResourceManager.GetString("Vaccinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your nearest health provider.
        /// </summary>
        public static string Vaccinate1 {
            get {
                return ResourceManager.GetString("Vaccinate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice translation.
        /// </summary>
        public static string Voice_Translation {
            get {
                return ResourceManager.GetString("Voice_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input your location here.
        /// </summary>
        public static string Watermark_Location {
            get {
                return ResourceManager.GetString("Watermark_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Empathi.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We help you connect with support organizations around Victoria.
        /// </summary>
        public static string Welcome1 {
            get {
                return ResourceManager.GetString("Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location.
        /// </summary>
        public static string Your_Location {
            get {
                return ResourceManager.GetString("Your_Location", resourceCulture);
            }
        }
    }
}
